config/routes.rb
Dinemedia::Application.routes.draw do
  
  match 'services'=> "home#services", :via => :get
  match 'portfolio'=> "home#portfolio", :via => :get
  match 'products' => "home#products", :via => :get
  match 'contact'=> "home#contact", :via => [:get,:post]
  post 'footer_contact'=> "home#footer_contact"
  root :to => "home#index"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessor :attach
#  apply_simple_captcha
  #  has_attached_file :attach, :styles => { :large => "640*480", :medium => "300*300>", :thumb => "100*100>" },
  #       :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
  #       :url => "/system/:attachment/:id/:style/:filename"
  validates :email, :presence => true, :email_format => true
  validates :name, :subject , :presence => true
  # validates_format_of :attach_file_name, :with => %r{\.(docx|doc|pdf)$}i,
  # :message => 'Only PDF, doc, docx or TEXT files are allowed. '
  # validates_attachment_presence :attach
  #  validates_attachment_content_type :attach, :content_type => ['application/pdf', 'text/plain'], :if => Proc.new { |module_file| !module_file.attach_file_name.blank? }, :message => "must be in '.pdf' format"
  after_save :send_mail
  def send_mail
   ContactMailer.contact(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SimpleCaptcha::ControllerHelpers
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :verify_authenticity_token
  def index
    
  end
  
  def services
    
  end
  
  def portfolio
    
  end
  
  def products
    
  end
  
  def contact
    if request.post?
      @contact = Contact.new(contact_params)
      if params[:contact][:attach].present?
        file_name = params[:contact][:attach].original_filename    
        file = params[:contact][:attach].read    
        file_type = file_name.split('.').last
        new_name_file = Time.now.to_i
        new_file_name_with_type = "#{new_name_file}." + file_type
        File.open("#{Rails.root.to_s}/public/system/attaches/#{new_file_name_with_type}", 'wb') {|f| f.write(file) }
        @contact.original_file_name = file_name
        @contact.attach_file_name = new_file_name_with_type
      end
      if simple_captcha_valid?
        if @contact.save
          flash.now[:notice] = 'Your Message Successfully Sent.'
          redirect_to contact_path
        else
        end
      else
        @contact.errors.add(:captcha,"not valid")
      end
    else
      @contact = Contact.new
    end
  end
  
  def footer_contact
    if request.post?
      @footer_contact = Contact.new(contact_params)
      if params[:contact][:attach].present?
        file_name = params[:contact][:attach].original_filename    
        file = params[:contact][:attach].read    
        file_type = file_name.split('.').last
        new_name_file = Time.now.to_i
        new_file_name_with_type = "#{new_name_file}." + file_type
        File.open("#{Rails.root.to_s}/public/system/attaches/#{new_file_name_with_type}", 'wb') {|f| f.write(file) }
        @footer_contact.original_file_name = file_name
        @footer_contact.attach_file_name = new_file_name_with_type
      end
      if simple_captcha_valid?
        if @footer_contact.save
          flash.now[:notice] = 'Your Message Successfully Sent.'
        else
        end
      else
        @footer_contact.errors.add(:captcha,"not valid")
      end
    else
      @footer_contact = Contact.new
    end
  end
  
  private
  def contact_params
    params.require(:contact).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contact_form.html.erb
<%= form_for(@contact,:as => :contact, :url => contact_path, :method => 'post', :html => { :multipart => true }) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p><%= f.text_field :name, :class => "input-nameContact form-poshytip", :title=>"Enter your full name", :placeholder=>"Name" %></p>
  <p><%= f.text_field :email, :class =>"input-nameContact form-poshytip", :title=>"Enter your email address", :placeholder=>"Email" %></p>
  <p><%= f.text_field :subject, :class =>"input-nameContact form-poshytip", :title=>"Enter your subject", :placeholder=>"Subject" %></p>
  <p><%= f.file_field :attach,:id => "web",:class=>"input-nameContact form-poshytip" %></p>
  <p><%= f.text_area :comment,:rows =>"5", :cols=>"20", :class=>"textarea-Contact form-poshytip",:id => "comments",:placeholder => "Message" %></p>
  <%= show_simple_captcha %>
  <p><input type="submit" value="Send" class="btn-send" name="submit" id="submit" /></p>
<% end %>

app/views/home/_technologies.html.erb
<div class="container">	
  <div class="content">
    <div class="box-technology box-technology-h">
      <div class="shadow"></div>
      <h3><em>Technology Stack</em></h3>
      <div class="list_carousel">
        <ul id="carousel-2" class="animation-div">
          <li><div><a href="javascript:void(0);" title="AJAX"><img src="/assets/technology_stack/ajax.png" alt="AJAX" title="AJAX"></a></div></li>	
          <li><div><a href="javascript:void(0);" title="amazon S3"><img src="/assets/technology_stack/amazonS3.png" alt="amazon S3" title="amazon S3"></a></div></li>
          <li><div><a href="javascript:void(0);" title="amcharts"><img src="/assets/technology_stack/amcharts.png" alt="amcharts" title="amcharts"></a></div></li>
          <li><div><a href="javascript:void(0);" title="Capistrano"><img src="/assets/technology_stack/capistrano.png" alt="Capistrano" title="Capistrano"></a></div></li>
          <li><div><a href="javascript:void(0);" title="CC Avenue"><img src="/assets/technology_stack/ccavenue.png" alt="CC Avenue" title="CC Avenue"></a></div></li>
          <li><div><a href="javascript:void(0);" title="Engine Yard"><img src="/assets/technology_stack/engineyard.png" alt="Engine Yard" title="Engine Yard"></a></div></li>
          <li><div><a href="javascript:void(0);" title="open-tok"><img src="/assets/technology_stack/opentok.png" alt="open-tok" title="open-tok"></a></div></li>
          <li><div><a href="javascript:void(0);" title="paypal"><img src="/assets/technology_stack/paypal.png" alt="paypal" title="paypal"></a></div></li>
          <li><div><a href="javascript:void(0);" title="jquery"><img src="/assets/technology_stack/jquery.png" alt="jquery" title="jquery"></a></div></li>				
          <li><div><a href="javascript:void(0);" title="Amazon Web Servics"><img src="/assets/technology_stack/amazon_webservics.png" alt="Amazon Web Servics" title="Amazon Web Servics"></a></div></li>
          <li><div><a href="javascript:void(0);" title="Apache Passenger"><img src="/assets/technology_stack/apache_passenger.png" alt="Apache Passenger" title="Apache Passenger"></a></div></li>
          <li><div><a href="javascript:void(0);" title="Bootstrap"><img src="/assets/technology_stack/bootstrap.png" alt="Bootstrap" title="Bootstrap"></a></div></li>
          <li><div><a href="javascript:void(0);" title="Cucumber"><img src="/assets/technology_stack/cucumber.png" alt="Cucumber" title="Cucumber"></a></div></li>
          <li><div><a href="javascript:void(0);" title="Github Social"><img src="/assets/technology_stack/github_social.png" alt="Github Social" title="Github Social"></a></div></li>
          <li><div><a href="javascript:void(0);" title="Google Analytics"><img src="/assets/technology_stack/google_analytics.png" alt="Google Analytics" title="Google Analytics"></a></div></li>
          <li><div><a href="javascript:void(0);" title="Google Chart"><img src="/assets/technology_stack/google_chart.png" alt="Google Chart" title="Google Chart"></a></div></li>
          <li><div><a href="javascript:void(0);" title="Heroku"><img src="/assets/technology_stack/heroku.png" alt="heroku" title="heroku"></a></div></li>
          <li><div><a href="javascript:void(0);" title="Java Script"><img src="/assets/technology_stack/java_script.png" alt="Java Script" title="Java Script"></a></div></li> 
          <li><div><a href="javascript:void(0);" title="Juggernaut"><img src="/assets/technology_stack/juggernaut.png" alt="Juggernaut" title="Juggernaut"></a></div></li> 
          <li><div><a href="javascript:void(0);" title="New Relic"><img src="/assets/technology_stack/new_relic.png" alt="New Relic" title="New Relic"></a></div></li>
          <li><div><a href="javascript:void(0);" title="Open Flesh Chart"><img src="/assets/technology_stack/open_flesh_chart.png" alt="New Relic" title="New Relic"></a></div></li>
          <li><div><a href="javascript:void(0);" title="Postgresql"><img src="/assets/technology_stack/postgresql.png" alt="Postgresql" title="Postgresql"></a></div></li> 
          <li><div><a href="javascript:void(0);" title="Prototype"><img src="/assets/technology_stack/prototype.png" alt="Prototype" title="Prototype"></a></div></li>
          <li><div><a href="javascript:void(0);" title="Radiant"><img src="/assets/technology_stack/radiant.png" alt="Radiant" title="Radiant"></a></div></li>
          <li><div><a href="javascript:void(0);" title="rspec"><img src="/assets/technology_stack/rspec.png" alt="rspec" title="rspec"></a></div></li>
          <li><div><a href="javascript:void(0);" title="spree"><img src="/assets/technology_stack/spree.png" alt="spree" title="spree"></a></div></li>
          <li><div><a href="javascript:void(0);" title="Sql Server"><img src="/assets/technology_stack/sql_server.png" alt="Sql Server" title="Sql Server"></a></div></li>
          <li><div><a href="javascript:void(0);" title="ssl"><img src="/assets/technology_stack/ssl.png" alt="ssl" title="ssl"></a></div></li>   
          <li><div><a href="javascript:void(0);" title="TYPO3"><img src="/assets/technology_stack/typo3.png" alt="TYPO3" title="TYPO3"></a></div></li> 
          <li><div><a href="javascript:void(0);" title="rackspace"><img src="/assets/technology_stack/rackspace.png" alt="rackspace" title="rackspace"></a></div></li> 						
        </ul>
        <div class="clearF"></div>
        <a id="carousel-prev-2" class="prev" href="javascript:void(0);">&lt;</a>
        <a id="carousel-next-2" class="next" href="javascript:void(0);">&gt;</a>
        <div id="pager-2" class="pager"></div>
      </div>
    </div>
    <div class="clearF"></div>
  </div>
</div>

app/views/home/contact.html.erb
<div class="container">   
  <div class="content">
    <div class="contact-leftColumn col-lg-8 col-md-6 col-sm-12">
      <div class="space-left">
        <h3><span>Get In Touch</span></h3>
          <%= render :partial => "home/contact_form" %>
      </div>
      <div class="clearF"></div>
    </div>
    <div class="contact-rightColumn col-lg-4 col-md-6 col-sm-12">
      <div class="space-left-service">
        <h3><span>Contact Information</span></h3>
        <ul class="list-contactInfo">
          <li class="icon-add">17 haugh Park, Longstone Road, Edinburgh, EH142Bd, Scotland United Kingdom</li>
          <li class="icon-phone">Phone: +447963120298/+447903113113</li>
          <li class="icon-email"><a href="mailto:contact@dine-media.com" title="contact@dine-media.com">contact@dine-media.com</a></li>
          <li class="icon-skype"><a title="rails.dev" href="javascript:void(0);">rails.dev</a></li>
        </ul>
        <div class="clearF"></div>
      </div>
    </div>     			
    <div class="clearF"></div>
  </div>		
</div>
<%= render "technologies" %>

app/views/home/footer_contact.js.erb
<% if @footer_contact.new_record? %>
  $('#contact_form').html('<%= escape_javascript(render :partial => "/layouts/contact_form") %>')
<% else %>
  window.location.reload();
<% end %>

app/views/layouts/_contact_form.html.erb
<div class="footerEmailBox col-lg-8 col-md-8 col-sm-8">
  <%= form_for(@footer_contact ||= Contact.new,:as => :contact, :url => footer_contact_path, :method => 'post', :html => { :multipart => true, :remote => true, :id => "contacts_form"}) do |f| %>
    <% if @footer_contact.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @footer_contact.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.text_field :name, :class => "input-name", :title=>"Enter your full name", :placeholder=>"Name (required)" %>
      <%= f.text_field :email, :class =>"input-name", :title=>"Enter your email address", :placeholder=>"Email (required)" %>
    </p>
    <p>
      <%= f.text_field :subject, :class =>"input-name", :title=>"Enter your subject", :placeholder=>"Subject" %>
      <%= f.file_field :attach,:id => "web",:class=>"input-name" %>
    </p>
    <p><%= f.text_area :comment,:rows =>"5", :cols=>"20", :class=>"textarea-message",:title => "Enter your Message",:id => "comments",:placeholder => "Message" %></p>
    <%= show_simple_captcha %>
    <div align="right"><%= f.submit :submit, :class=>"btn-send" %></div>
  <% end %>
</div>

app/views/simple_captcha/_simple_captcha.erb
<style type="text/CSS">
  .simple_captcha{padding: 0 23px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>
  
  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>
  
  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>
</div>